{ pkgs
, ...
}:
let
  username = "amerino";
in
{
  nix.settings.trusted-users = [ "${username}" ];

  users = {
    groups = {
      ${username} = { };
      docker = { };
    };

    # set user's default shell system-wide
    defaultUserShell = pkgs.zsh;

    # Define a user account. Don't forget to set a password with ‘passwd’.
    users.${username} = {
      # the hashed password with salt is generated by run `mkpasswd`.
      hashedPassword = "$y$j9T$agtPmdg/aOFzaPb8tNPF5.$sks0UhDeWiXL88SfuYbYJAkR0nme5UsKSO/2thOwdL8";
      home = "/home/${username}";
      isNormalUser = true;
      description = "Default user";
      extraGroups = [
        "${username}"
        "users"
        "networkmanager"
        "wheel"
        "docker"
        "adbusers"
        "libvirtd"
      ];
    };
  };
}
